//
//  KQHomeViewController.swift
//  KQTaskProject
//
//  Created by KamsQue on 22/12/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol KQHomeDisplayLogic: AnyObject
{
    func displayFetchedUsers(viewModel: KQHome.HomeUsers.ViewModel)
    func stopUrlSession(isCanceled:Bool)
}

class KQHomeViewController: KQSuperVC, KQHomeDisplayLogic
{
    
    
    var interactor: KQHomeBusinessLogic?
    var homeServices : HomeServices?
    var router: (NSObjectProtocol & KQHomeRoutingLogic & KQHomeDataPassing)?
    var selectedUser : User?
    // MARK: - Properties
    
    lazy var tableView : UITableView = {     // view
        let view = UITableView()
        
        view.translatesAutoresizingMaskIntoConstraints = false
        view.register(KQContactTableViewCell.self, forCellReuseIdentifier: KQContactTableViewCell.identifire)
        view.dataSource = self
        return  view
    }()
    
    var displayUsers : [User]? // model
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let presenter = KQHomePresenter()
        let interactor = KQHomeInteractor(presenter: presenter)
        let router = KQHomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        //        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - SetUp Navigation
    private func setUpNavigation() {
        navigationItem.title = "Users List"
    }
    
    // MARK: - Private Actions
    private func configureUI() {
        // The .xib files should have the same name as the class file
        setTableViewConstraint()
        tableView.delegate = self
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        setUpNavigation()
        configureUI()
        accessibility()
    }
    
    private func accessibility(){
        self.view.isAccessibilityElement = true
        self.view.accessibilityLabel = "KQHomeViewController"
        tableView.isAccessibilityElement = true
        tableView.accessibilityLabel = "tableView"
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.view.isUserInteractionEnabled = true
        self.tableView.isUserInteractionEnabled = true
        fetchUsers()
    }
    
    // MARK: Fetch Users
    
    func fetchUsers()
    {
        let request = KQHome.HomeUsers.Request()
        LoadingOverlay.shared.showOverlay(view: self.view)
        LoadingOverlay.shared.activityIndicator.startAnimating()
        self.tableView.isUserInteractionEnabled = false
        interactor?.fetchUsers(request: request)
        
    }
    // MARK: Display Users
    func displayFetchedUsers(viewModel: KQHome.HomeUsers.ViewModel)
    {
        self.displayUsers = viewModel.users
        DispatchQueue.main.async() {
            self.tableView.reloadData()
            LoadingOverlay.shared.activityIndicator.stopAnimating()
            LoadingOverlay.shared.hideOverlayView()
            self.tableView.isUserInteractionEnabled = true
        }
    }
    
    func moveToItemDetails(selectedUser:User?) {
        //        DispatchQueue.main.asyncAfter(deadline: .now()) {  [weak self] in
        //            // your code here
        //
        //        }
        
        if var rout = self.router{
            rout.dataStore?.selectedUser = selectedUser
            rout.routeToDetails(segue: nil)
        }
    }
    
    func stopUrlSessionInit(){
        self.tableView.isUserInteractionEnabled = true
        interactor?.stopUrlSessionInit()
    }
    
    func stopUrlSession(isCanceled: Bool) {
        self.tableView.isUserInteractionEnabled = false
        LoadingOverlay.shared.activityIndicator.stopAnimating()
        LoadingOverlay.shared.hideOverlayView()
        moveToItemDetails(selectedUser: selectedUser)
    }
}

extension KQHomeViewController{
    // MARK: - SetConstraint
    func setTableViewConstraint(){
        view.backgroundColor = AppTheme.shared.navBackgroundColor
        tableView.isAccessibilityElement = true
        view.isAccessibilityElement = true
        self.view.addSubview(tableView)
        NSLayoutConstraint.activate([
            tableView.topAnchor.constraint(equalTo:view.safeAreaLayoutGuide.topAnchor),
            tableView.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor),
            tableView.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor),
            tableView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
        ])
    }
}

// MARK: - UITableViewDataSource and UITableViewDelegate
extension KQHomeViewController : UITableViewDataSource, UITableViewDelegate{
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return displayUsers?.count ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCell(withIdentifier: KQContactTableViewCell.identifire, for: indexPath) as! KQContactTableViewCell
        
        cell.selectedUser = displayUsers?[indexPath.row]
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        100
    }
    
    func tableView(_ tableView: UITableView, estimatedHeightForRowAt indexPath: IndexPath) -> CGFloat {
        return 100
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        selectedUser = displayUsers?[indexPath.row]
        if var rout = self.router{
            rout.dataStore?.selectedUser = selectedUser
            rout.routeToDetails(segue: nil)
        }
        //        if LoadingOverlay.shared.activityIndicator.isAnimating{
        //            stopUrlSessionInit()
        //        }else{
        //            self.tableView.isUserInteractionEnabled = true
        //            moveToItemDetails(selectedUser: selectedUser)
        //        }
    }
}

