//
//  KQHomePresenter.swift
//  KQTaskProject
//
//  Created by KamsQue on 22/12/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol KQHomePresentationLogic
{
    func presentSomething(response: KQHome.Api.Response)
    func stopApiCallSuccess(isCanceled: Bool)
    
}

class KQHomePresenter: KQHomePresentationLogic
{
    weak var viewController: KQHomeDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: KQHome.Api.Response)
    {
        let viewModel = KQHome.Api.ViewModel(users: response.homeUsers)
        viewController?.displayHomeList(viewModel: viewModel)
    }
    func stopApiCallSuccess(isCanceled:Bool){
        viewController?.stopApiCallSuccess(isCanceled: isCanceled)
    }
}
