//
//  KQHomeInteractor.swift
//  KQTaskProject
//
//  Created by KamsQue on 22/12/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol KQHomeBusinessLogic
{
  func doSomething(request: KQHome.Something.Request)
}

protocol KQHomeDataStore
{
  //var name: String { get set }
}

class KQHomeInteractor: KQHomeBusinessLogic, KQHomeDataStore
{
  var presenter: KQHomePresentationLogic?
  var worker: KQHomeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: KQHome.Something.Request)
  {
    worker = KQHomeWorker()
    worker?.doSomeWork()
    
    let response = KQHome.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
