//
//  KQUserModels.swift
//  KQTaskProject
//
//  Created by KamsQue on 22/12/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


enum KQHome {
    // MARK: Use cases
    
    enum HomeUsers {
        struct Request {
            
        }
        // MARK: - Home
        struct Response {
            var homeUsers : [User]?
        }
        
        struct ViewModel {
            struct DisplayUser {
                var displayUser: User?
            }
            var users: [User]?
        }
    }
}
