//
//  KQItemDetailsPresenter.swift
//  KQTaskProject
//
//  Created by KamsQue on 22/12/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol KQItemDetailsPresentationLogic
{
  func presentSomething(response: KQItemDetails.Model.Response)
}

class KQItemDetailsPresenter: KQItemDetailsPresentationLogic
{
  weak var viewController: KQItemDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: KQItemDetails.Model.Response)
  {
      let viewModel = KQItemDetails.Model.ViewModel(selectedUser: response.selectedUser)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
