//
//  KQItemDetailsModels.swift
//  KQTaskProject
//
//  Created by KamsQue on 22/12/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum KQItemDetails
{
    // MARK: Use cases
    
    enum Model
    {
        struct Request
        {
        }
        struct Response
        {
            var selectedUser : User?
        }
        struct ViewModel
        {
            var selectedUser : User?
        }
    }
}
