//
//  KQItemDetailsInteractor.swift
//  KQTaskProject
//
//  Created by KamsQue on 22/12/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol KQItemDetailsBusinessLogic
{
    func doSomething(request: KQItemDetails.Something.Request)
}

protocol KQItemDetailsDataStore
{
    var selectedUser: Post? { get set }
}

class KQItemDetailsInteractor: KQItemDetailsBusinessLogic, KQItemDetailsDataStore
{
    var selectedUser: Post?
    var presenter: KQItemDetailsPresentationLogic?
    var worker: KQItemDetailsWorker?
    
    // MARK: Do something
    
    func doSomething(request: KQItemDetails.Something.Request)
    {
        worker = KQItemDetailsWorker()
        worker?.doSomeWork()
        
        let response = KQItemDetails.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
