//
//  KQUserDetailsPresenter.swift
//  KQTaskProject
//
//  Created by KamsQue on 22/12/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol KQUserDetailsPresentationLogic
{
    func presentUserDetails(response: KQUserDetailsModels.Model.Response)
    func presentRequestValidationError(isValidated:Bool)
    func presenApiNetworkError(message: String?)
    func checkApiUrlSerssion(isCanceled: Bool)
}

class KQUserDetailsPresenter: KQUserDetailsPresentationLogic
{
    
    weak var viewController: KQUserDetailsDisplayLogic?
    
    // MARK: present User Details
    
    func presentUserDetails(response: KQUserDetailsModels.Model.Response)
    {
        let viewModel = KQUserDetailsModels.Model.ViewModel(selectedUser : response.selectedUser , userDetails: response.userDetails)
        viewController?.displayUserDetails(viewModel: viewModel)
    }
    
    func presentRequestValidationError(isValidated: Bool) {
        viewController?.displayValidationError(isValidated: isValidated)
    }
    
    func checkApiUrlSerssion(isCanceled:Bool){
        viewController?.checkApiUrlSerssion(isCanceled: isCanceled)
    }
    
    func presenApiNetworkError(message: String?) {
        viewController?.presenApiNetworkError(message: message)
    }
}
