//
//  KQUserDetailsInteractor.swift
//  KQTaskProject
//
//  Created by KamsQue on 22/12/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol KQUserDetailsBusinessLogic
{
    func displayUserData(userDetails:UserDetails?)
    func getUserDetailsApi(request: KQUserDetailsModels.Model.Request)
    func userstopApiCallStart()
}

protocol KQUserDetailsDataStore
{
    var selectedUser: User? { get set }
}

class KQUserDetailsInteractor: KQUserDetailsBusinessLogic, KQUserDetailsDataStore
{
    var selectedUser: User?
    var presenter: KQUserDetailsPresentationLogic?
    var worker: KQUserDetailsWorker?
    var userBusiness = UserBusiness()
    
    // MARK: get User Details Api
    
    func getUserDetailsApi(request: KQUserDetailsModels.Model.Request){
        worker = KQUserDetailsWorker()
        worker?.validateRequest(request: request, completion: { isValidate in
            if isValidate{
                self.userBusiness.userDetailsApiCall(parameters: ["loginId":(request.loginId ?? "") as String]) { userDetails, error in
                    self.displayUserData(userDetails: userDetails)
                }
            }else{
                self.presenter?.presentRequestValidationError(isValidated: isValidate)
            }
        })
    }
    
    // MARK: display User Data
    
    func displayUserData(userDetails:UserDetails?)
    {
        let response = KQUserDetailsModels.Model.Response(selectedUser: selectedUser , userDetails: userDetails)
        presenter?.presentUserDetails(response: response)
    }
    
    func userstopApiCallStart(){
        self.userBusiness.userstopApiCallStart { isCanceled in
            self.presenter?.stopApiCallSuccess(isCanceled: isCanceled)
        }
    }
}
