//
//  KQHomePresenterTests.swift
//  KQTaskProject
//
//  Created by KamsQue on 24/12/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import KQTaskProject
import XCTest

class KQHomePresenterTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: KQHomePresenter!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupKQHomePresenter()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupKQHomePresenter()
    {
        sut = KQHomePresenter()
    }
    
    // MARK: Test doubles
    
    class KQHomeDisplayLogicSpy: KQHomeDisplayLogic
    {
        // MARK: Method call expectations
        
        var displayFetchedUsersCalled = false
        
        // MARK: Argument expectations
        
        var viewModel: KQHome.HomeUsers.ViewModel!
        
        // MARK: Spied methods
        
        func displayFetchedUsers(viewModel: KQTaskProject.KQHome.HomeUsers.ViewModel) {
            displayFetchedUsersCalled = true
            self.viewModel = viewModel
        }
        
        func stopUrlSession(isCanceled: Bool) {
            print(isCanceled)
        }
    }
    
    // MARK: Tests
    
    func testPresentFetchedUsersShouldAskViewControllerToDisplayFetchedUsers()
    {
        // Given
        let listKQHomeDisplayLogicSpy = KQHomeDisplayLogicSpy()
        sut.viewController = listKQHomeDisplayLogicSpy
        
        // When
        let users = [User(login: "Login",url: "google.com")]
        let response = KQHome.HomeUsers.Response(homeUsers: users)
        sut.presentUsers(response: response)
        
        // Then
        XCTAssert(listKQHomeDisplayLogicSpy.displayFetchedUsersCalled, "Presenting fetched users should ask view controller to display them")
    }
}
