//
//  KQUserDetailsWorkerTests.swift
//  KQTaskProject
//
//  Created by KamsQue on 25/12/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import KQTaskProject
import XCTest

class KQUserDetailsWorkerTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: KQUserDetailsWorker!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupKQUserDetailsWorker()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupKQUserDetailsWorker()
    {
        sut = KQUserDetailsWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testValidateUserDetailsRequesteSuccess()
    {
        
        // Given
        var loginId : String?
        var IsValidate = false
        
        loginId = "mojombo"
        // When
        sut.validateRequest(request: KQUserDetailsModels.Model.Request(loginId: loginId)) { isValidate in
            print(isValidate)
            IsValidate = isValidate
        }
        // Then
        XCTAssertTrue(IsValidate, "Worker will Validate Success full if  User Request login id based has String should")
    }
    
    
    func testValidateUserDetailsRequesteError()
    {
        // Given
        var loginId : String?
        var IsValidate = false
        loginId = nil
        // When
        sut.validateRequest(request: KQUserDetailsModels.Model.Request(loginId: loginId)) { isValidate in
            print(isValidate)
            IsValidate = isValidate
        }
        // Then
        XCTAssertFalse(IsValidate, "Worker will Validate as Error if User Request login id has nil value")
    }
}
