//
//  HomeVCInteractor.swift
//  KQTaskProject
//
//  Created by KamsQue on 22/12/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeVCBusinessLogic
{
  func doSomething(request: HomeVC.Something.Request)
}

protocol HomeVCDataStore
{
  //var name: String { get set }
}

class HomeVCInteractor: HomeVCBusinessLogic, HomeVCDataStore
{
  var presenter: HomeVCPresentationLogic?
  var worker: HomeVCWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: HomeVC.Something.Request)
  {
    worker = HomeVCWorker()
    worker?.doSomeWork()
    
    let response = HomeVC.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
